version: '3'
services:
  db:
    image: mysql:5.7.31
    volumes:
      - ./dev_env/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root 
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  client:
    image: goservice-dev:latest
    stdin_open: true
    tty: true
    command: /bin/sh
    depends_on: 
      - db
    volumes:
      - .:/app
